server:
  port: 8080

bot.token: ${TOKEN_TELEGRAM}

spring:
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USER}
    password: ${RABBIT_PASS}

queue.url.send: ${QUEUE_URL:jarvis.send.telegram}
